import { NextResponse, type NextRequest } from "next/server";
import { DEVICE_COOKIE_NAME, claimDevice } from "@/lib/deviceAuth";

// POST /api/kiosk/claim — ADR-0015 Phase 3. Deliberately unauthenticated: an
// iPad that's never been signed into anything exchanges a one-time setup
// code (generated by an admin in the Devices settings page) for a device
// token, stored as an httpOnly cookie. The code is single-use (claimDevice
// nulls it on success) and short-lived (15 min), which bounds brute-force
// risk without needing a separate rate-limiter — there's no other
// persistent-store infra in this app to build one on top of yet.
const COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 365; // 1 year — revoked via the admin UI, not expiry

export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null);
  const code = typeof body?.code === "string" ? body.code : "";
  if (!code.trim()) {
    return NextResponse.json({ error: "Enter the setup code from your admin." }, { status: 400 });
  }

  const claimed = await claimDevice(code);
  if (!claimed) {
    return NextResponse.json(
      { error: "That code is invalid or has expired. Ask an admin for a new one." },
      { status: 400 }
    );
  }

  const response = NextResponse.json({ deviceName: claimed.deviceName });
  response.cookies.set(DEVICE_COOKIE_NAME, claimed.token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: COOKIE_MAX_AGE_SECONDS,
  });
  return response;
}
